export const cuisineList = [
    "African",
    "American",
    "Andhra",
    "Arabian",
    "Asian",
    "Bakery and Confectionary",
    "Barbecue",
    "Bengali",
    "Bihari",
    "Biryani",
    "Burger",
    "Chettinad",
    "Chinese",
    "Coffee",
    "Continental",
    "Deli",
    "Desserts",
    "Doughnuts",
    "European",
    "Fast Food",
    "Finger Food",
    "French",
    "Fusion",
    "Goan",
    "Gujarati",
    "Health Food",
    "Hyderabadi",
    "Ice Cream",
    "Indian Cuisine",
    "Indonesian",
    "Iranian",
    "Italian",
    "Japanese",
    "Juice",
    "Kashmiri",
    "Kerala",
    "Korean",
    "Lebanese",
    "Lucknowi",
    "Malaysian",
    "Mediterranean",
    "Mexican",
    "Middle Eastern",
    "Mithai",
    "Modern Indian",
    "Mughlai",
    "Multi-Cuisine",
    "Naga",
    "Nepalese",
    "North Eastern",
    "North Indian",
    "Oriental",
    "Pizza",
    "Portuguese",
    "Rajasthani",
    "Seafood",
    "Shakes",
    "Singaporean",
    "Sizzlers",
    "South American",
    "South Indian",
    "Spanish",
    "Street Food",
    "Sushi",
    "Tea",
    "Tex Mex",
    "Thai",
    "Tibetan",
    "Turkish",
    "Vietnamese",
    "Waffle",
    "World Cuisine"
];
