export const cuisineList = [
    "Butter Chicken",  
    "Hyderabadi Biryani",
    "Masala Dosa",
    "Rogan Josh",
    "Palak Paneer",
    "Chole Bhature",
    "Malai Kofta",
    "Rajasthani Dal Baati Churma",
    "Pav Bhaji",
    "Dhokla  ",
    "Goan Fish Curry",
    "Aloo Paratha",
    "Kolkata Biryani",
    "Macher Jhol",
    "Sarson ka Saag and Makki ki Roti",
    "Chettinad Chicken",
    "Vada Pav",
    "Idli Sambar",
    "Gajar ka Halwa",
    "Pesarattu  ",
    "Mysore Pak",
    "Litti Chokha",
    "Appam with Stew",
    "Vindaloo",
    "Bahubali Thali",
    "Dal Bhaat",
    "Khichdi"
]